# Generated by Django 3.0.6 on 2020-05-18 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Currency code must be 3 letters uppercase.', regex='^[A-Z]{3}$')])),
                ('target', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Currency code must be 3 letters uppercase.', regex='^[A-Z]{3}$')])),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
